/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "tertiary-fixed-dim": "#cbd5e1",
                "secondary-fixed": "#c7d2fe",
                "surface-tint": "#38c8fc",
                "on-tertiary-container": "#94a3b8",
                "surface-container-lowest": "#ffffff",
                "primary": "#38c8fc",
                "primary-fixed": "#e2e8f0",
                "error-container": "#ffdad6",
                "on-secondary-container": "#ffffff",
                "secondary-container": "#4f46e5",
                "secondary": "#6366f1",
                "on-surface": "#38c8fc",
                "surface-container-low": "#f8fafc",
                "on-secondary-fixed": "#312e81",
                "on-primary-fixed": "#020617",
                "error": "#ba1a1a",
                "surface-container-highest": "#e2e8f0",
                "inverse-on-surface": "#f1f5f9",
                "tertiary-fixed": "#e2e8f0",
                "secondary-fixed-dim": "#818cf8",
                "on-primary": "#ffffff",
                "surface": "#f8fafc",
                "surface-dim": "#cbd5e1",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#1e293b",
                "outline-variant": "#cbd5e1",
                "tertiary": "#334155",
                "on-tertiary-fixed-variant": "#475569",
                "on-tertiary-fixed": "#0f172a",
                "surface-variant": "#f1f5f9",
                "primary-container": "#1e293b",
                "on-surface-variant": "#38c8fc",
                "outline": "#64748b",
                "surface-container": "#f1f5f9",
                "on-error-container": "#93000a",
                "on-background": "#38c8fc",
                "on-secondary": "#ffffff",
                "on-error": "#ffffff",
                "on-primary-container": "#94a3b8",
                "surface-bright": "#ffffff",
                "on-secondary-fixed-variant": "#4338ca",
                "background": "#f8fafc",
                "surface-container-high": "#e2e8f0",
                "inverse-primary": "#94a3b8",
                "tertiary-container": "#1e293b",
                "primary-fixed-dim": "#94a3b8",
                "on-primary-fixed-variant": "#334155"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "base": "8px",
                "container-max": "1280px",
                "margin-desktop": "32px",
                "gutter": "24px",
                "margin-mobile": "16px"
            },
            fontFamily: {
                "display-lg-mobile": ["Inter"],
                "body-sm": ["Inter"],
                "label-md": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "body-md": ["Inter"],
                "headline-md": ["Inter"],
                "label-sm": ["Inter"],
                "display-lg": ["Inter"]
            },
            fontSize: {
                "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "600" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
            }
        }
    },
    plugins: [],
}